language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - caoxudong818@gmail.com
      - caoxudong818@163.com
    #on_success: [always|never|change] # default: change
    on_failure: [always] # default: always
